/* Generated By:JavaCC: Do not edit this line. MyToken.cc Version 8.0.0 */
/* JavaCCOptions:STATIC=true,SUPPORT_CLASS_VISIBILITY_PUBLIC=true,INCLUDE_FOR_TOKEN=null,TOKEN_SUPER_CLASS= */
#include "MyToken.h"
namespace FOO {
	namespace BAR {
		MyToken::MyToken() :
			_beginLine(0), _beginColumn(0), _endLine(0), _endColumn(0)
		{
			this->_kind = 0;
			this->_next = nullptr;
			this->_specialToken = nullptr;
		}

		MyToken::MyToken(int kind) :
			_beginLine(0), _beginColumn(0), _endLine(0), _endColumn(0)
		{
			this->_kind = kind;
			this->_next = nullptr;
			this->_specialToken = nullptr;
		}

		MyToken::MyToken(int kind, const JJString& image)
			: _beginLine(0), _beginColumn(0), _endLine(0), _endColumn(0)
		{
			this->_kind = kind;
			this->_image = image;
			this->_next = nullptr;
			this->_specialToken = nullptr;
		}

		MyToken* MyToken::newToken(int kind, const JJString& image)
		{
			switch (kind)
			{
			default: return new MyToken(kind, image);
			}
		}

		MyToken* MyToken::newToken(int kind)
		{
			return newToken(kind, JJString());
		}

		MyToken::~MyToken() {
			if (_specialToken) delete _specialToken;
			this->_kind = 0;
			this->_next = nullptr;
			this->_specialToken = nullptr;
		}

		int& 					MyToken::kind() { return _kind; }
		int& 					MyToken::beginLine() { return _beginLine; }
		int& 					MyToken::beginColumn() { return _beginColumn; }
		int& 					MyToken::endLine() { return _endLine; }
		int& 					MyToken::endColumn() { return _endColumn; }
		JJString& 				MyToken::image() { return _image; }
		Basic::Token*& 			MyToken::next() { return _next; }
		Basic::Token*& 			MyToken::specialToken() { return _specialToken; }

		const int& 				MyToken::kind() const { return _kind; }
		const int& 				MyToken::beginLine() const { return _beginLine; }
		const int& 				MyToken::beginColumn() const { return _beginColumn; }
		const int& 				MyToken::endLine() const { return _endLine; }
		const int& 				MyToken::endColumn() const { return _endColumn; }
		const JJString& 		MyToken::image() const { return _image; }
		const Basic::Token* 	MyToken::next() const { return _next; }
		const Basic::Token*		MyToken::specialToken() const { return _specialToken; }

		const JJString& 		MyToken::toString() { return _image; }

		void*& 					MyToken::value() { return _value; }
		const void* 			MyToken::value() const { return _value; }

	}
}
/* JavaCC - OriginalChecksum=9436fc46454be004c97bbc7e79c818d5 (do not edit this line) */
